local lib_name = "LibCustomIcons"
local lib = _G[lib_name]
local s = lib.GetStaticTable()
local a = lib.GetAnimatedTable()

s["@Anorage"] = "LibCustomIcons/icons/misc7/Anorage_2.dds"
s["@Axe_Zuffs"] = "LibCustomIcons/icons/misc7/Axe_Zuffs.dds"
s["@nitm4r3"] = "LibCustomIcons/icons/misc7/nitm4r3.dds"
s["@Vilooo"] = "LibCustomIcons/icons/misc7/Vilooo.dds"
s["@oScorpio"] = "LibCustomIcons/icons/misc7/oScorpio.dds"
s["@IAstronomicanI"] = "LibCustomIcons/icons/misc7/IAstronomicanI.dds"
s["@Debuffed"] = "LibCustomIcons/icons/misc7/Debuffed.dds"
s["@lKalahari"] = "LibCustomIcons/icons/misc7/lKalahari.dds"
s["@Maccies"] = "LibCustomIcons/icons/misc7/Maccies.dds"
s["@Jdaytona"] = "LibCustomIcons/icons/misc7/Jdaytona.dds"
s["@Mayhem86"] = "LibCustomIcons/icons/misc7/Mayhem86.dds"
s["@Razor1991"] = "LibCustomIcons/icons/misc7/Razor1991.dds"
s["@Yunaalescaa"] = "LibCustomIcons/icons/misc7/Yunaalescaa.dds"
s["@AimboBaggins"] = "LibCustomIcons/icons/misc7/AimboBaggins.dds"
s["@Megatreck8"] = "LibCustomIcons/icons/misc7/Megatreck8.dds"
s["@SladkiyDistroy"] = "LibCustomIcons/icons/misc7/SladkiyDistroy.dds"
s["@Prxvokedlegend"] = "LibCustomIcons/icons/misc7/Prxvokedlegend.dds"
s["@Ak4r1"] = "LibCustomIcons/icons/misc7/Ak4r1.dds"
s["@Prof_Flausch"] = "LibCustomIcons/icons/misc7/prof_flausch.dds"
s["@Ravnic93"] = "LibCustomIcons/icons/misc7/ravnic93.dds"
s["@Tomharken"] = "LibCustomIcons/icons/misc7/Tomharken.dds"
s["@BULLAVAS"] = "LibCustomIcons/icons/misc7/BULLAVAS.dds"
s["@LittleESO"] = "LibCustomIcons/icons/misc7/LittleESO.dds"
s["@Boxis"] = "LibCustomIcons/icons/misc7/Boxis.dds"
s["@Circuitous"] = "LibCustomIcons/icons/misc7/Circuitous.dds"
s["@TAISELE"] = "LibCustomIcons/icons/misc7/TAISELE.dds"
s["@SedationMaster"] = "LibCustomIcons/icons/misc7/SedationMaster.dds"
s["@breadandmllk"] = "LibCustomIcons/icons/misc7/breadandmllk.dds"
s["@madmufffin"] = "LibCustomIcons/icons/misc7/madmufffin.dds"
s["@someone_unknown"] = "LibCustomIcons/icons/misc7/someone_unknown.dds"
s["@VaLeeeT"] = "LibCustomIcons/icons/misc7/VaLeeeT.dds"
s["@Toweliewahn"] = "LibCustomIcons/icons/misc7/Toweliewahn.dds"
s["@Shae.Vizla"] = "LibCustomIcons/icons/misc7/Shae.Vizla.dds"
s["@LunarKitsune"] = "LibCustomIcons/icons/misc7/LunarKitsune.dds"
s["@eileen_bck"] = "LibCustomIcons/icons/misc7/eileen_bck.dds"
s["@Antonyfly"] = "LibCustomIcons/icons/misc7/Antonyfly.dds"
s["@GL0O"] = "LibCustomIcons/icons/misc7/GL0O.dds"
s["@alansgaming"] = "LibCustomIcons/icons/misc7/alansgaming.dds"
s["@Lukion04"] = "LibCustomIcons/icons/misc7/Lukion04.dds"
s["@Minhoca420"] = "LibCustomIcons/icons/misc7/Minhoca420.dds"
s["@Oxi4an"] = "LibCustomIcons/icons/misc7/Oxi4an.dds"
s["@Diemente"] = "LibCustomIcons/icons/misc7/Diemente.dds"
s["@JalaBenjo"] = "LibCustomIcons/icons/misc7/JalaBenjo.dds"
s["@lid_lid"] = "LibCustomIcons/icons/misc7/lid_lid.dds"
s["@Im_Churro"] = "LibCustomIcons/icons/misc7/Im_Churro.dds"
s["@Oonora"] = "LibCustomIcons/icons/misc7/Oonora.dds"
s["@SkyFox_01"] = "LibCustomIcons/icons/misc7/SkyFox_01.dds"
s["@didntgetpillager"] = "LibCustomIcons/icons/misc7/didntgetpillager.dds"
s["@issavo"] = "LibCustomIcons/icons/misc7/issavo.dds"
s["@AloAlo"] = "LibCustomIcons/icons/misc7/AloAlo.dds"
s["@xColorovy"] = "LibCustomIcons/icons/misc7/xColorovy.dds"
s["@efiye"] = "LibCustomIcons/icons/misc7/efiye.dds"
s["@SophieRain"] = "LibCustomIcons/icons/misc7/SophieRain.dds"
s["@Bleek707"] = "LibCustomIcons/icons/misc7/Bleek707.dds"
s["@Always_Atlas"] = "LibCustomIcons/icons/misc7/Always_Atlas.dds"
s["@DownZi"] = "LibCustomIcons/icons/misc7/DownZi.dds"
s["@SassyFluffington"] = "LibCustomIcons/icons/misc7/SassyFluffington.dds"
s["@Orllyon"] = "LibCustomIcons/icons/misc7/Orllyon.dds"
s["@Mr.Maxie"] = "LibCustomIcons/icons/misc7/Mr.Maxie.dds"
s["@TheInquisitiveSpoon"] = "LibCustomIcons/icons/misc7/TheInquisitiveSpoon.dds"
s["@shigeatzu"] = "LibCustomIcons/icons/misc7/shigeatzu.dds"
s["@BayzBlackBaccara"] = "LibCustomIcons/icons/misc7/BayzBlackBaccara.dds"
s["@Sai_ESO"] = "LibCustomIcons/icons/misc7/Sai_ESO.dds"
s["@Qkzzz"] = "LibCustomIcons/icons/misc7/Qkzzz.dds"
s["@Kqzzz"] = "LibCustomIcons/icons/misc7/Kqzzz.dds"
s["@DovakiinFawad"] = "LibCustomIcons/icons/misc7/DovakiinFawad.dds"
s["@dianabz"] = "LibCustomIcons/icons/misc7/dianabz.dds"
s["@Abi_raga"] = "LibCustomIcons/icons/misc7/Abi_raga.dds"
s["@PinduriBerkenye"] = "LibCustomIcons/icons/misc7/PinduriBerkenye.dds"
s["@TheMemeLord27"] = "LibCustomIcons/icons/misc7/TheMemeLord27.dds"
s["@harueee"] = "LibCustomIcons/icons/misc7/harueee.dds"
s["@BosmerBathWater"] = "LibCustomIcons/icons/misc7/BosmerBathWater.dds"
a["@NumberOneZergling"] = {"LibCustomIcons/icons/misc7/NumberOneZergling_anim.dds", 16, 2, 16}
a["@Fishy399"] = {"LibCustomIcons/icons/misc7/Fishy399_anim.dds", 2, 2, 17}
a["@PiscesIII"] = {"LibCustomIcons/icons/misc7/PiscesIII_anim.dds", 3, 2, 33}
a["@DanoFett"] = {"LibCustomIcons/icons/misc7/DanoFett_anim.dds", 10, 5, 15}
a["@bi0skill3r"] = {"LibCustomIcons/icons/misc7/bi0skill3r_anim.dds", 7, 4, 10}
a["@ScaRlet9512"] = {"LibCustomIcons/icons/misc7/ScaRlet9512_anim.dds", 6, 2, 10}
a["@lKalahari"] = {"LibCustomIcons/icons/misc7/lKalahari_anim.dds", 17, 2, 16}
a["@sekikamisama"] = {"LibCustomIcons/icons/misc7/sekikamisama_anim.dds", 10, 2, 20}
a["@Ponsie"] = {"LibCustomIcons/icons/misc7/Ponsie_anim.dds", 2, 2, 5}
a["@Blaze03"] = {"LibCustomIcons/icons/misc7/Blaze03_anim.dds", 5, 2, 25}
a["@oDutt"] = {"LibCustomIcons/icons/misc7/oDutt_anim.dds", 16, 2, 17}
a["@Volderam"] = {"LibCustomIcons/icons/misc7/Volderam_anim.dds", 17, 1, 10}
a["@DrGaricus"] = {"LibCustomIcons/icons/misc7/DrGaricus_anim.dds", 5, 1, 10}
a["@gettin_fresh"] = {"LibCustomIcons/icons/misc7/gettin_fresh_anim.dds", 10, 2, 20}
a["@Ayonnis"] = {"LibCustomIcons/icons/misc7/Ayonnis_anim.dds", 7, 3, 7}
a["@fdk123"] = {"LibCustomIcons/icons/misc7/fdk123_anim.dds", 3, 1, 2}
a["@h-Gecko"] = {"LibCustomIcons/icons/misc7/h-Gecko_anim.dds", 7, 7, 14}
a["@RealLoveBVB"] = {"LibCustomIcons/icons/misc7/RealLoveBVB_anim.dds", 7, 2, 32}
a["@Sc1lla"] = {"LibCustomIcons/icons/misc7/Sc1lla_anim.dds", 10, 5, 20}
a["@PaganPandas"] = {"LibCustomIcons/icons/misc7/PaganPandas_anim_2.dds", 10, 5, 33}
a["@CedrazGil"] = {"LibCustomIcons/icons/misc7/CedrazGil_anim.dds", 9, 2, 33}
a["@veludelu"] = {"LibCustomIcons/icons/misc7/veludelu_anim.dds", 6, 5, 10}
a["@OmnipotentYouthSocie"] = {"LibCustomIcons/icons/misc7/OmnipotentYouthSocie_anim.dds", 5, 4, 10}
a["@iimTaylor"] = {"LibCustomIcons/icons/misc7/iimTaylor_anim.dds", 3, 3, 8}
a["@p0rk"] = {"LibCustomIcons/icons/misc7/p0rk_anim.dds", 3, 1, 5}
a["@Root118"] = {"LibCustomIcons/icons/misc7/Root118_anim.dds", 13, 2, 6}
a["@Shirogami107"] = {"LibCustomIcons/icons/misc7/Shirogami107_anim.dds", 5, 3, 15}
a["@Passaringo"] = {"LibCustomIcons/icons/misc7/Passaringo_anim.dds", 10, 5, 20}
a["@Plies"] = {"LibCustomIcons/icons/misc7/Plies_anim.dds", 7, 1, 9}
a["@Anastesia69"] = {"LibCustomIcons/icons/misc7/Anastesia69_anim.dds", 10, 5, 10}
a["@EchoWFlechazo"] = {"LibCustomIcons/icons/misc7/EchoWFlechazo_anim.dds", 10, 5, 10}
a["@VerifiedToy"] = {"LibCustomIcons/icons/misc7/VerifiedToy_anim.dds", 5, 2, 9}
a["@Haikyuu_929"] = {"LibCustomIcons/icons/misc7/Haikyuu_929_anim.dds", 32, 1, 17}
a["@iiTzChriss"] = {"LibCustomIcons/icons/misc7/iiTzChriss_anim.dds", 5, 2, 17}
a["@Exosq"] = {"LibCustomIcons/icons/misc7/Exosq_anim.dds", 9, 2, 9}
a["@Mizeov"] = {"LibCustomIcons/icons/misc7/Mizeov_anim.dds", 7, 6, 13}
a["@zuxyq"] = {"LibCustomIcons/icons/misc7/zuxyq_anim.dds", 6, 1, 20}
a["@ComandoAlpha"] = {"LibCustomIcons/icons/misc7/ComandoAlpha_anim.dds", 7, 7, 10}
a["@Balfgur"] = {"LibCustomIcons/icons/misc7/Balfgur_anim.dds", 5, 2, 25}
a["@arcadeslum"] = {"LibCustomIcons/icons/misc7/arcadeslum_anim.dds", 7, 7, 20}
a["@xSi1ver"] = {"LibCustomIcons/icons/misc7/xSi1ver_anim.dds", 23, 2, 14}
a["@oAMo"] = {"LibCustomIcons/icons/misc7/oAMo_anim.dds", 19, 1, 12.5}
a["@riminise"] = {"LibCustomIcons/icons/misc7/riminise_anim.dds", 7, 7, 16}
a["@Innsmaut"] = {"LibCustomIcons/icons/misc7/innsmaut_anim.dds", 6, 1, 8}
a["@Stakan9000"] = {"LibCustomIcons/icons/misc7/Stakan9000_anim.dds", 5, 3, 47}
a["@MiguelCura"] = {"LibCustomIcons/icons/misc7/MiguelCura_anim.dds", 5, 2, 14}
a["@PinduriBerkenye"] = {"LibCustomIcons/icons/misc7/PinduriBerkenye_anim.dds", 7, 2, 11}
a["@Loreuh"] = {"LibCustomIcons/icons/misc7/Loreuh_anim.dds", 5, 2, 33}
a["@Noobl3t"] = {"LibCustomIcons/icons/misc7/Noobl3t_anim.dds", 9, 5, 13}
s["@Sbirr0"] = "LibCustomIcons/icons/misc7/Sbirr0.dds"
s["@Eilistraae"] = "LibCustomIcons/icons/misc7/Eilistraae.dds"
a["@damage_1"] = {"LibCustomIcons/icons/misc7/damage_1_anim.dds", 11, 1, 17}
a["@Perxie"] = {"LibCustomIcons/icons/misc7/Perxie_anim.dds", 8, 1, 20}
s["@AlsClarity"] = "LibCustomIcons/icons/misc7/AlsClarity.dds"
a["@Malkovva"] = {"LibCustomIcons/icons/misc7/Malkovva_anim.dds", 11, 3, 50}
a["@MissMya"] = {"LibCustomIcons/icons/misc7/MissMya_anim.dds", 9, 1, 18}
a["@DEATH_SHAD0W226"] = {"LibCustomIcons/icons/misc7/DEATH_SHAD0W226_anim.dds", 30, 1, 10}
a["@Pegno"] = {"LibCustomIcons/icons/misc7/Pegno_anim.dds", 16, 2, 10}
a["@Tang015"] = {"LibCustomIcons/icons/misc7/Tang015_anim.dds", 13, 1, 14}
s["@babak.babak"] = "LibCustomIcons/icons/misc7/babak.babak.dds"
s["@pyrolah"] = "LibCustomIcons/icons/misc7/pyrolah.dds"
s["@Master_Merlyn"] = "LibCustomIcons/icons/misc7/Master_Merlyn.dds"
s["@CoCo_OwO"] = "LibCustomIcons/icons/misc7/CoCo_OwO.dds"
a["@Whytuck"] = {"LibCustomIcons/icons/misc7/whytuck_anim.dds", 25, 2, 25}
a["@Jasper0729"] = {"LibCustomIcons/icons/misc7/Jasper0729_anim.dds", 47, 1, 14}
s["@Yuhaa"] = "LibCustomIcons/icons/misc7/Yuhaa.dds"
s["@Rexeyas"] = "LibCustomIcons/icons/misc7/Rexeyas.dds"
s["@adis3636"] = "LibCustomIcons/icons/misc7/adis3636.dds"
s["@doctorosen"] = "LibCustomIcons/icons/misc7/doctorosen.dds"
s["@Shadorein"] = "LibCustomIcons/icons/misc7/Shadorein.dds"
a["@Rainbow_Stay"] = {"LibCustomIcons/icons/misc7/Rainbow_Stay_anim.dds", 41, 1, 25}
a["@LordDraw"] = {"LibCustomIcons/icons/misc7/LordDraw_anim.dds", 74, 3, 20}
s["@Lil_Moham"] = "LibCustomIcons/icons/misc7/Lil_Moham.dds"
s["@rimuru552"] = "LibCustomIcons/icons/misc7/rimuru552.dds"
a["@Princess-Roxxie"] = {"LibCustomIcons/icons/misc7/Princess-Roxxie_anim.dds", 5, 2, 10}
a["@Havoc.1412"] = {"LibCustomIcons/icons/misc7/Havoc.1412_anim.dds", 7, 7, 25}
a["@JayyMi"] = {"LibCustomIcons/icons/misc7/JayyMi_anim.dds", 23, 6, 20}
s["@korgaard"] = "LibCustomIcons/icons/misc7/korgaard.dds"
s["@TimistGOTT"] = "LibCustomIcons/icons/misc7/TimistGOTT.dds"
a["@TimistGOTT"] = {"LibCustomIcons/icons/misc7/TimistGOTT_anim.dds", 10, 6, 33}
a["@PvPenny"] = {"LibCustomIcons/icons/misc7/PvPenny_anim.dds", 3, 2, 10}
s["@UncleFoxx"] = "LibCustomIcons/icons/misc7/UncleFoxx.dds"
s["@JacobWasTake'n"] = "LibCustomIcons/icons/misc7/JacobWasTaken.dds"
s["@kamikiro"] = "LibCustomIcons/icons/misc7/kamikiro.dds"
s["@RashEnderSami"] = "LibCustomIcons/icons/misc7/RashEnderSami.dds"